import { NextResponse } from 'next/server';
import { FieldValue } from 'firebase-admin/firestore';
import { adminDb } from '../../../../../../lib/firebase-admin';
import { requirePlayer } from '../../../../../../lib/player-auth';
import { fallbackPlayerName, playerDisplayProfiles } from '../../../../../../lib/player-profiles';

export const runtime = 'nodejs';
const headers = { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'content-type, authorization' };
export function OPTIONS() { return new NextResponse(null, { headers }); }
export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) { if (!adminDb) return NextResponse.json({ error: 'Lore service is not configured.' }, { status: 503, headers }); const { id } = await params, snapshot = await adminDb.collection('lores').doc(id).collection('comments').orderBy('createdAt', 'desc').limit(50).get(); const profiles = await playerDisplayProfiles(snapshot.docs.map(doc => doc.data().authorId).filter((authorId): authorId is string => typeof authorId === 'string'), new Map(snapshot.docs.map(doc => [doc.data().authorId, doc.data().authorEmail ?? '']))); return NextResponse.json({ comments: snapshot.docs.map(doc => { const data = doc.data(), profile = typeof data.authorId === 'string' ? profiles.get(data.authorId) : undefined; return { id: doc.id, text: data.text, author: profile?.username ?? data.author ?? fallbackPlayerName(data.authorEmail ?? ''), avatarUrl: profile?.avatarUrl ?? null, authorId: data.authorId ?? null, createdAt: data.createdAt?.toDate?.().toISOString() ?? null }; }) }, { headers }); }
export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) { try { if (!adminDb) throw new Error('Lore service is not configured.'); const player = await requirePlayer(request); const { id } = await params, { text } = await request.json(); if (typeof text !== 'string' || !text.trim() || text.length > 1000) throw new Error('Invalid comment.'); const lore = adminDb.collection('lores').doc(id), data = (await lore.get()).data(); if (!data || data.status !== 'Published') throw new Error('Lore not found.'); const profile = (await playerDisplayProfiles([player.id], new Map([[player.id, player.email]]))).get(player.id), author = profile?.username ?? fallbackPlayerName(player.email), ref = await lore.collection('comments').add({ text: text.trim(), author, authorId: player.id, authorEmail: player.email, createdAt: FieldValue.serverTimestamp() }); await lore.update({ commentCount: FieldValue.increment(1) }); return NextResponse.json({ id: ref.id, text: text.trim(), author, avatarUrl: profile?.avatarUrl ?? null, authorId: player.id, createdAt: new Date().toISOString() }, { headers }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : 'Comment failed.' }, { status: 401, headers }); } }
