'use client';
import { FormEvent,useEffect,useMemo,useState } from 'react';
import { confirmSignIn,fetchAuthSession,signIn,signOut } from 'aws-amplify/auth';
import { ImagePlus,Pencil,Plus,RefreshCw,Search,ShieldCheck,Sparkles,Trash2 } from 'lucide-react';
import { configureAuth,authConfigured } from '../lib/auth';
import { ADMIN_GROUP_NAME } from '../lib/admin-constants';
import type { Character } from '../lib/character';
import { AdminShell,PageHeader } from '../components/admin-shell';
import { EmptyState,LoadingScreen,Notice,Spinner } from '../components/admin-ui';
import { CharacterEditor } from '../components/character-editor';

export default function Home(){
 const[mode,setMode]=useState<'login'|'new-password'>('login'),[authenticated,setAuthenticated]=useState(false),[authReady,setAuthReady]=useState(false),[authBusy,setAuthBusy]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[newPassword,setNewPassword]=useState('');
 const[characters,setCharacters]=useState<Character[]>([]),[selected,setSelected]=useState<Character|null>(null),[editing,setEditing]=useState<Character|null>(null),[query,setQuery]=useState(''),[status,setStatus]=useState<'All'|'Published'|'Draft'>('All'),[notice,setNotice]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{void(async()=>{if(!authConfigured()||!configureAuth()){setAuthenticated(true);setAuthReady(true);return}try{const token=(await fetchAuthSession()).tokens?.idToken;const groups=token?.payload['cognito:groups'];if(token&&Array.isArray(groups)&&groups.includes(ADMIN_GROUP_NAME)){setAuthenticated(true)}else if(token){await signOut();setNotice('This account is not an administrator. Sign in with an admin account.')}}finally{setAuthReady(true)}})()},[]);
 useEffect(()=>{if(authenticated)void load()},[authenticated]);
 const visible=useMemo(()=>characters.filter(item=>(item.name+' '+item.title+' '+item.tags.join(' ')).toLowerCase().includes(query.toLowerCase())&&(status==='All'||item.status===status)),[characters,query,status]);
 async function api(path:string,options?:RequestInit){const token=authConfigured()?(await fetchAuthSession()).tokens?.idToken?.toString():undefined;return fetch(path,{...options,headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`} :{}),...options?.headers}})}
 async function load(){setLoading(true);try{const response=await api('/api/characters'),data=await response.json();if(!response.ok)throw new Error(data.error);setCharacters(data.characters??[]);setSelected(current=>current?(data.characters??[]).find((item:Character)=>item.id===current.id)??null:(data.characters??[])[0]??null)}catch(error){setNotice(error instanceof Error?error.message:'Could not load characters.')}finally{setLoading(false)}}
 async function finishAdminSignIn(){const token=(await fetchAuthSession()).tokens?.idToken;const groups=token?.payload['cognito:groups'];if(!token||!Array.isArray(groups)||!groups.includes(ADMIN_GROUP_NAME)){await signOut();throw new Error('This account is not an administrator. Ask an existing admin for access.')}setAuthenticated(true);setPassword('');setNewPassword('');setMode('login')}
 async function authenticate(event:FormEvent){event.preventDefault();setAuthBusy(true);setNotice('');try{if(!configureAuth()){setAuthenticated(true);return}if(mode==='new-password'){const result=await confirmSignIn({challengeResponse:newPassword});if(!result.isSignedIn)throw new Error(`Sign-in needs another step: ${result.nextStep.signInStep}`);await finishAdminSignIn();return}const result=await signIn({username:email,password});if(!result.isSignedIn&&result.nextStep.signInStep==='CONFIRM_SIGN_IN_WITH_NEW_PASSWORD_REQUIRED'){setNewPassword('');setMode('new-password');setNotice('Your invitation uses a temporary password. Choose a new password to continue.');return}if(!result.isSignedIn)throw new Error(`Sign-in needs another step: ${result.nextStep.signInStep}`);await finishAdminSignIn()}catch(error){setNotice(error instanceof Error?error.message:'Authentication failed.')}finally{setAuthBusy(false)}}
 async function save(value:Character){try{const exists=characters.some(item=>item.id===value.id),response=await api(exists?`/api/characters/${value.id}`:'/api/characters',{method:exists?'PATCH':'POST',body:JSON.stringify(value)}),data=await response.json();if(!response.ok)throw new Error(data.error);setCharacters(items=>exists?items.map(item=>item.id===value.id?data:item):[data,...items]);setSelected(data);setNotice(`${value.name} was saved.`);return true}catch(error){setNotice(error instanceof Error?error.message:'Could not save character.');return false}}
 async function remove(character:Character){if(!confirm(`Delete ${character.name}? Its S3 image will also be removed.`))return;const response=await api(`/api/characters/${character.id}`,{method:'DELETE'}),data=await response.json();if(!response.ok)return setNotice(data.error);const remaining=characters.filter(item=>item.id!==character.id);setCharacters(remaining);setSelected(remaining[0]??null);setEditing(null)}
 if(!authReady)return <LoadingScreen/>;
 if(!authenticated)return <AuthScreen mode={mode} setMode={setMode} email={email} setEmail={setEmail} password={password} setPassword={setPassword} newPassword={newPassword} setNewPassword={setNewPassword} busy={authBusy} notice={notice} submit={authenticate}/>;
 const create=()=>{setSelected(null);setEditing({id:crypto.randomUUID(),name:'',title:'',bio:'',status:'Draft',tags:[],updated:'Just now'})};
 return <AdminShell onSignedOut={()=>setAuthenticated(false)}><PageHeader eyebrow="AMBAVERSE / CHARACTERS" title="Characters" count={characters.length} description="Select a character to view or edit its profile." action={<button className="button primary" onClick={create}><Plus size={17}/>Add character</button>}/><Notice>{notice}</Notice><div className="admin-toolbar"><label className="search-control"><Search size={17}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search characters"/></label><select value={status} onChange={event=>setStatus(event.target.value as typeof status)}><option>All</option><option>Published</option><option>Draft</option></select><button className="icon-button" onClick={()=>void load()} disabled={loading}>{loading?<Spinner/>:<RefreshCw size={17}/>}</button><span>{visible.length} of {characters.length}</span></div>{loading&&!characters.length?<div className="section-loader"><Spinner label="Loading characters"/></div>:<div className="character-split"><aside className="character-list"><div className="lore-list-heading"><strong>All characters</strong><span>{visible.length}</span></div>{visible.map(character=><button key={character.id} className={selected?.id===character.id&&!editing?'active':''} onClick={()=>{setSelected(character);setEditing(null)}}><span className="character-list-thumb">{character.imageUrl?<img src={character.imageUrl} alt=""/>:<ImagePlus size={18}/>}</span><span><strong>{character.name}</strong><small>{character.status} · {character.title||'No title'}</small></span></button>)}{!visible.length&&<p className="lore-list-empty">No matching characters.</p>}</aside><section className="character-detail-pane">{editing?<CharacterEditor inline character={editing} close={()=>setEditing(null)} save={save}/>:selected?<CharacterView character={selected} edit={()=>setEditing({...selected})} remove={()=>void remove(selected)}/>:<EmptyState title="Choose a character" description="Select an item from the list or create a new character." action={<button className="button primary" onClick={create}><Plus size={17}/>Add character</button>}/>}</section></div>}</AdminShell>
}

function CharacterView({character,edit,remove}:{character:Character;edit:()=>void;remove:()=>void}){return <article className="character-admin-view"><div className="detail-actions"><span className={`status ${character.status.toLowerCase()}`}>{character.status}</span><button className="button ghost" onClick={edit}><Pencil size={16}/>Edit</button><button className="icon-button danger" onClick={remove}><Trash2 size={16}/></button></div><div className="character-hero">{character.imageUrl?<img src={character.imageUrl} alt={character.name}/>:<div><ImagePlus size={32}/></div>}</div><p className="eyebrow">{character.title||'AMBAVERSE CHARACTER'}</p><h2>{character.name}</h2><div className="tag-row">{character.tags.map(tag=><span key={tag}>{tag}</span>)}</div><div className="character-admin-bio">{character.bio||'No biography has been added yet.'}</div><footer>Updated {character.updated}</footer></article>}

function AuthScreen(props:{mode:'login'|'new-password';setMode:(value:'login'|'new-password')=>void;email:string;setEmail:(value:string)=>void;password:string;setPassword:(value:string)=>void;newPassword:string;setNewPassword:(value:string)=>void;busy:boolean;notice:string;submit:(event:FormEvent)=>Promise<void>}){
 const{mode,setMode,email,setEmail,password,setPassword,newPassword,setNewPassword,busy,notice,submit}=props;
 const[confirmPassword,setConfirmPassword]=useState(''),[passwordError,setPasswordError]=useState('');
 function handleSubmit(event:FormEvent){if(mode==='new-password'&&newPassword!==confirmPassword){event.preventDefault();setPasswordError('Passwords do not match.');return}setPasswordError('');void submit(event)}
 function backToSignIn(){setPasswordError('');setConfirmPassword('');setNewPassword('');setMode('login')}
 return <main className="auth-page"><section className="auth-brand"><span className="brand-mark"><Sparkles/></span><p className="eyebrow">AMBATUAPP / ADMIN</p><h1>Shape the<br/><em>Ambaverse.</em></h1></section><section className="auth-panel"><form onSubmit={handleSubmit}><p className="eyebrow">{mode==='login'?'WELCOME BACK':'FIRST SIGN IN'}</p><h2>{mode==='login'?'Sign in to continue':'Choose a new password'}</h2><p className="muted">{mode==='login'?'Use the account assigned to your team.':'Set a personal password to finish accepting your admin invitation.'}</p><label>Email<input type="email" value={email} onChange={event=>setEmail(event.target.value)} disabled={busy||mode==='new-password'} autoComplete="username" required/></label>{mode==='login'?<label>Password<input type="password" value={password} onChange={event=>setPassword(event.target.value)} minLength={8} autoComplete="current-password" required/></label>:<><label>New password<input type="password" value={newPassword} onChange={event=>{setNewPassword(event.target.value);setPasswordError('')}} minLength={8} autoComplete="new-password" required/></label><label>Confirm new password<input type="password" value={confirmPassword} onChange={event=>{setConfirmPassword(event.target.value);setPasswordError('')}} minLength={8} autoComplete="new-password" aria-invalid={Boolean(passwordError)} required/></label></>}<Notice>{passwordError||notice}</Notice><button className="button primary full" disabled={busy}>{busy?<Spinner label="Please wait"/>:mode==='login'?'Sign in':'Set password'}</button>{mode==='new-password'&&<button type="button" className="button link full" onClick={backToSignIn} disabled={busy}>Back to sign in</button>}</form></section></main>
}
