'use client';
import { FormEvent,useState } from 'react';
import { Check,ImagePlus,X } from 'lucide-react';
import { fetchAuthSession } from 'aws-amplify/auth';
import { authConfigured } from '../lib/auth';
import type { Character } from '../lib/character';
import { Spinner } from './admin-ui';
export function CharacterEditor({character,close,save,inline=false}:{character:Character;close:()=>void;save:(value:Character)=>Promise<boolean>;inline?:boolean}){
 const[draft,setDraft]=useState(character),[preview,setPreview]=useState(character.imageUrl),[tagInput,setTagInput]=useState(''),[uploading,setUploading]=useState(false),[saving,setSaving]=useState(false),[uploadNote,setUploadNote]=useState('');
 const set=(key:keyof Character,value:string)=>setDraft(current=>({...current,[key]:value}));
 function addTag(value=tagInput){const tag=value.trim();if(tag&&!draft.tags.some(item=>item.toLowerCase()===tag.toLowerCase()))setDraft(current=>({...current,tags:[...current.tags,tag]}));setTagInput('')}
 async function upload(file?:File){if(!file)return;setPreview(URL.createObjectURL(file));setUploading(true);setUploadNote('');try{const token=authConfigured()?(await fetchAuthSession()).tokens?.idToken?.toString():undefined,response=await fetch('/api/character-images/presign',{method:'POST',headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})},body:JSON.stringify({fileName:file.name,contentType:file.type,characterId:draft.id})}),data=await response.json();if(!response.ok)throw new Error(data.error);const put=await fetch(data.uploadUrl,{method:'PUT',headers:{'content-type':file.type},body:file});if(!put.ok)throw new Error('S3 upload failed.');setDraft(current=>({...current,imageKey:data.key}));setUploadNote('Uploaded to S3.')}catch(error){setUploadNote(error instanceof Error?error.message:'Image upload failed.')}finally{setUploading(false)}}
 async function submit(event:FormEvent){event.preventDefault();const pending=tagInput.trim(),tags=pending&&!draft.tags.some(item=>item.toLowerCase()===pending.toLowerCase())?[...draft.tags,pending]:draft.tags;setSaving(true);const ok=await save({...draft,tags,updated:'Just now'});setSaving(false);if(ok)close()}
 const form=<form className={`editor ${inline?'character-inline-editor':''}`} onSubmit={submit}><div className="modal-header"><div><p className="eyebrow">AMBAVERSE / CHARACTER</p><h2>{character.name?'Edit character':'New character'}</h2></div><button className="icon-button" type="button" onClick={close}><X size={19}/></button></div><label className="image-picker">{preview?<img src={preview} alt="Character preview"/>:<span><ImagePlus size={26}/></span>}<div><strong>{uploading?'Uploading…':'Choose portrait'}</strong><small>{uploadNote||'JPG, PNG, or WEBP'}</small></div><input type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>void upload(event.target.files?.[0])} disabled={saving||uploading}/></label><div className="form-grid"><label>Name<input value={draft.name} onChange={event=>set('name',event.target.value)} required/></label><label>Role / title<input value={draft.title} onChange={event=>set('title',event.target.value)} required/></label></div><label>Biography<textarea value={draft.bio} onChange={event=>set('bio',event.target.value)} rows={8}/></label><div className="form-grid"><label>Tags<div className="tag-input"><div>{draft.tags.map(tag=><span key={tag}>{tag}<button type="button" onClick={()=>setDraft(current=>({...current,tags:current.tags.filter(item=>item!==tag)}))}><X size={11}/></button></span>)}</div><input value={tagInput} onChange={event=>setTagInput(event.target.value)} onBlur={()=>addTag()} onKeyDown={event=>{if(event.key==='Enter'||event.key===','){event.preventDefault();addTag()}}} placeholder="Type then press Enter"/></div></label><label>Status<select value={draft.status} onChange={event=>set('status',event.target.value)}><option>Draft</option><option>Published</option></select></label></div><div className="modal-actions"><button type="button" className="button ghost" onClick={close}>Cancel</button><button className="button primary" disabled={saving||uploading}>{saving?<Spinner label="Saving"/>:<><Check size={17}/>Save character</>}</button></div></form>;
 return inline?form:<div className="modal-backdrop">{form}</div>
}
