import { NextResponse } from 'next/server';
import { FieldValue } from 'firebase-admin/firestore';
import { adminDb } from '../../../../lib/firebase-admin';
import { requireAdmin } from '../../../../lib/api-auth';
import { deleteCharacterImage, signedCharacterImageUrl } from '../../../../lib/s3-images';
import { LORE_TEXT_LIMIT } from '../../../../lib/lore';

export const runtime = 'nodejs';
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { try { await requireAdmin(request); if (!adminDb) return NextResponse.json({ error: 'Firestore is not configured.' }, { status: 503 }); const body = await request.json(); if (typeof body.text !== 'string' || !body.text.trim()) throw new Error('Lore text is required.'); if (body.text.length > LORE_TEXT_LIMIT) throw new Error(`Lore text cannot exceed ${LORE_TEXT_LIMIT.toLocaleString()} characters.`); const { imageUrls: _imageUrls, ...update } = body; const { id } = await params; await adminDb.collection('lores').doc(id).set({ ...update, updatedAt: FieldValue.serverTimestamp(), updated: 'Just now' }, { merge: true }); const data = (await adminDb.collection('lores').doc(id).get()).data()!; const keys = Array.isArray(data.imageKeys) ? data.imageKeys : []; return NextResponse.json({ id, ...data, imageUrls: await Promise.all(keys.map(signedCharacterImageUrl)) }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : 'Request failed' }, { status: 400 }); } }
export async function DELETE(request: Request, { params }: { params: Promise<{ id: string }> }) { try { await requireAdmin(request); if (!adminDb) return NextResponse.json({ error: 'Firestore is not configured.' }, { status: 503 }); const { id } = await params; const ref = adminDb.collection('lores').doc(id); const data = (await ref.get()).data(); if (!data) return NextResponse.json({ error: 'Lore not found.' }, { status: 404 }); const keys = Array.isArray(data.imageKeys) ? data.imageKeys.filter((key): key is string => typeof key === 'string') : []; await Promise.all(keys.map(deleteCharacterImage)); await ref.delete(); return NextResponse.json({ id }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : 'Request failed' }, { status: 400 }); } }
